services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 2s
      timeout: 2s
      retries: 30

  repo:
    build: ./repo
    environment:
      DB_DSN: postgres://app:app@db:5432/appdb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  order-service:
    build: ./order-service
    environment:
      REPO_URL: http://repo:8090
    depends_on:
      - repo
    ports:
      - "8081:8081"

  executor-service:
    build: ./executor-service
    environment:
      REPO_URL: http://repo:8090
    depends_on:
      - repo
    ports:
      - "8082:8082"

  logistics-service:
    build: ./logistics-service
    environment:
      REPO_URL: http://repo:8090
    depends_on:
      - repo
    ports:
      - "8083:8083"

  loadgen-orders:
    build: ./loadgens/loadgen-orders
    environment:
      TARGET_URL: http://order-service:8081
    depends_on:
      - order-service
    profiles: ["loadgen"]

  loadgen-executors:
    build: ./loadgens/loadgen-executors
    environment:
      TARGET_URL: http://executor-service:8082
    depends_on:
      - executor-service
    profiles: ["loadgen"]

  loadgen-logistics:
    build: ./loadgens/loadgen-logistics
    environment:
      ORDER_URL: http://order-service:8081
      EXECUTOR_URL: http://executor-service:8082
      LOGISTICS_URL: http://logistics-service:8083
    depends_on:
      - logistics-service
      - order-service
      - executor-service
    profiles: ["loadgen"]

volumes:
  pgdata: